### ISSUE TITLE
A1 might fail to launch

### ISSUE THREAD

**Issue by JohnDMcMaster** [Labsmore/pyuscope#172]
Possibly related to NA? Need more info

**Comment by JohnDMcMaster** [comment]
@yusufm please provide more info

**Comment by JohnDMcMaster** [comment]
made a test case for a similar microscope, confirmed there is an issue

```
mcmaster@thudpad:~/doc/ext/pyuscope$ ./app/argus.py --microscope 20mp
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
qt5ct: using qt5ct plugin
Status: Idle
qt5ct: D-Bus global menu: no
Traceback (most recent call last):
  File "/home/mcmaster/doc/ext/pyuscope/uscope/app/argus/main.py", line 310, in main
    gstwidget_main(MainWindow, parse_args=parse_args)
  File "/home/mcmaster/doc/ext/pyuscope/uscope/gui/gstwidget.py", line 788, in gstwidget_main
    _mainwin = AQMainWindow(**kwargs)
  File "/home/mcmaster/doc/ext/pyuscope/uscope/app/argus/main.py", line 48, in __init__
    self.post_ui_init()
  File "/home/mcmaster/doc/ext/pyuscope/uscope/app/argus/main.py", line 250, in post_ui_init
    tab.post_ui_init()
  File "/home/mcmaster/doc/ext/pyuscope/uscope/app/argus/widgets.py", line 1170, in post_ui_init
    awidgets_post_ui_init(self.awidgets)
  File "/home/mcmaster/doc/ext/pyuscope/uscope/app/argus/widgets.py", line 1075, in awidgets_post_ui_init
    awidget.post_ui_init()
  File "/home/mcmaster/doc/ext/pyuscope/uscope/app/argus/widgets.py", line 119, in post_ui_init
    self.reload_obj_cb()
  File "/home/mcmaster/doc/ext/pyuscope/uscope/app/argus/widgets.py", line 126, in reload_obj_cb
    for objective in self.ac.usc.get_scaled_objectives(self.ac.microscope):
  File "/home/mcmaster/doc/ext/pyuscope/uscope/config.py", line 733, in get_scaled_objectives
    self.scale_objectives_1x(objectives)
  File "/home/mcmaster/doc/ext/pyuscope/uscope/config.py", line 694, in scale_objectives_1x
    objective["um_per_pixel"] = um_per_pixel_raw_1x / objective[
KeyError: 'magnification'

ERROR 'magnification'
```

**Comment by JohnDMcMaster** [comment]
modified sm3590t_template.py to add add magnification key and regenerated the config file
