### ISSUE TITLE
Machine without z axis can crash

### ISSUE THREAD

**Issue by JohnDMcMaster** [Labsmore/pyuscope#284]
```
ryancor@ubuntu:~/Desktop/pyuscope$ app/argus.py 
FIXME WARNING: paramiko import failed
pygame 2.4.0 (SDL 2.26.4, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
grbl: failed to respond, attempting reset recovery
grbl: recovered after 1.387 sec
GRBL homing w/ INIT_LOCK, main status: Idle
Traceback (most recent call last):
  File "/home/ryancor/Desktop/pyuscope/uscope/app/argus/main.py", line 305, in main
    gstwidget_main(MainWindow, parse_args=parse_args)
  File "/home/ryancor/Desktop/pyuscope/uscope/gui/gstwidget.py", line 799, in gstwidget_main
    _mainwin = AQMainWindow(**kwargs)
  File "/home/ryancor/Desktop/pyuscope/uscope/app/argus/main.py", line 56, in __init__
    self.post_ui_init()
  File "/home/ryancor/Desktop/pyuscope/uscope/app/argus/main.py", line 258, in post_ui_init
    self.ac.post_ui_init()
  File "/home/ryancor/Desktop/pyuscope/uscope/app/argus/common.py", line 240, in post_ui_init
    self.microscope.configure()
  File "/home/ryancor/Desktop/pyuscope/uscope/microscope.py", line 89, in configure
    configure_motion_hal(self)
  File "/home/ryancor/Desktop/pyuscope/uscope/motion/plugins.py", line 102, in configure_motion_hal
    microscope.motion.configure(options=options)
  File "/home/ryancor/Desktop/pyuscope/uscope/motion/hal.py", line 455, in configure
    self._configured()
  File "/home/ryancor/Desktop/pyuscope/uscope/motion/grbl.py", line 1070, in _configured
    self.calc_steps_per_mm()
  File "/home/ryancor/Desktop/pyuscope/uscope/motion/grbl.py", line 1082, in calc_steps_per_mm
    steps_per_mm["z"] *= scalars["z"]
KeyError: 'z'

ERROR 'z'
```

**Comment by JohnDMcMaster** [comment]
This should be fixed now, just need to verify on real hardware

**Comment by JohnDMcMaster** [comment]
should be fixed
