### ISSUE TITLE
Review LS-HVY-123 support

### ISSUE THREAD

**Issue by JohnDMcMaster** [Labsmore/pyuscope#285]
Some potential issues:
- No homing switches. Are we sure these won't accidentally home? Should be really sure as a crash will destroy the coupling and total the stage
- Some corner cases around no z axis. Maybe just add a fake z axis? They don't home so it wouldn't hurt

**Comment by JohnDMcMaster** [comment]
tried homing and got this:

```
error:5
```

which translates to:

```
    5: "Homing fail. Homing not enabled in settings",
```

A few thoughts:
- We should explicitly not home on these systems to be 100% sure
- We should have caught the homing error

**Comment by JohnDMcMaster** [comment]
Looks like if you force a home the error is reported correctly:

```
$ ./test/grbl/home.py
Opening as GRBL object
Open ok
Traceback (most recent call last):
  File "./test/grbl/home.py", line 34, in <module>
    main()
  File "./test/grbl/home.py", line 31, in main
    grbl.gs.h()
  File "/home/mcmaster/doc/ext/pyuscope/uscope/motion/grbl.py", line 522, in h
    lines = self.txrxs("$H", trim_data=False, timeout=180)
  File "/home/mcmaster/doc/ext/pyuscope/uscope/motion/grbl.py", line 369, in txrxs
    raise GrblError(l)
uscope.motion.grbl.GrblError: error 5 (Homing fail. Homing not enabled in settings)
```
It doesn't force a home under a Microscope configuration because INIT_LOCK was set which means we can explicitly query the homing status. However homing is disabled on the GRBL controller so it reports ready to go (status Idle as opposed to Alarm):

```
$ ./test/grbl/home.py --microscope ls-hvy-1
Opening as GrblHal object
GRBL homing w/ INIT_LOCK, main status: Idle
```

**Comment by JohnDMcMaster** [comment]
In any case I've added a new config directive that will skip homing at startup:

```
$ ./test/grbl/home.py --microscope ls-hvy-1
Opening as GrblHal object
Homing: skip on no limit switches
```

If you tell the system to force a home it will complain angrily:

```
$ ./test/grbl/home.py --microscope ls-hvy-1 --force
Opening as GrblHal object
Homing: skip on no limit switches
Traceback (most recent call last):
  File "./test/grbl/home.py", line 34, in <module>
    main()
  File "./test/grbl/home.py", line 26, in main
    microscope.motion.home(force=args.force)
  File "/home/mcmaster/doc/ext/pyuscope/uscope/motion/grbl.py", line 1208, in home
    assert not force, "Requested homing on a system that can't home"
AssertionError: Requested homing on a system that can't home
```

**Comment by JohnDMcMaster** [comment]
I've added config.limit_switches, config.axes which should also help with some of the other issues. CLI run seems to work but needs to be tested on full system

However I'm also mingled this in with some unrelated jog changed so need to finish that before merge...

**Comment by JohnDMcMaster** [comment]
The jog code is merged along with these changes. Just needs to be tested on real LS-HVY-123 before merge

**Comment by JohnDMcMaster** [comment]
Should review machine limits as these I believe are mostly ignored but may at least trigger an assertion. And they may see more use in the future

**Comment by JohnDMcMaster** [comment]
I did a round of testing on LS-HVY-123. But others should probably still walk an update with me
