### ISSUE TITLE
Investigate memory corruption

### ISSUE THREAD

**Issue by JohnDMcMaster** [Labsmore/pyuscope#398]
Reports / data:
- Fiducial test was showing huge memory corruption in output images and IIRC something else (camera disconnects?). However, this was dismissed at the time due to questions over OpenCV thread safety
- Possibly results in a camera disconnect https://github.com/Labsmore/pyuscope/issues/366
- Can crash at exit somewhat regularly. I ignored this as its "only cleanup" but this might be a good place to start
-edgetriggered report below

Proposals:
-Code review for GUI elements accessed out of main thread. The core log() function is a good place to start
- Run profiling tools (valgrind, etc)
- Revisit fiducial test, which was known to cause bad corruption

Report from edgetriggered:

```
*** stack smashing detected ***: terminated             Traceback (most recent call last):                        File "/usr/lib/python3.11/site-packages/uscope/imagep/pipeline.py", line 114, in run                              ret = plugin.run(data_in=ip_params.data_in,                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^           File "/usr/lib/python3.11/site-packages/uscope/imagep/plugins.py", line 84, in run                                self._run(data_in, data_out, options=options)         File "/usr/lib/python3.11/site-packages/uscope/imagep/plugins.py", line 197, in _run                              check_call(args)                                    /usr/bin/pyuscope: line 2: 107669 Killed                  ./app/argus.py
```

Fiducial test:
- A "stress test"
- Takes lots of images
- Random quick movements (EMI?)
- Uses OpenCV in the scripting tab. Is this thread safe? OpenCV GUI is definitely not and will result in a crash

**Comment by JohnDMcMaster** [comment]
Example of shutdown crash:

```
Shutting down: requesting
Shutting down: joining
Joined
The program 'python3' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 449 error_code 9 request_code 130 minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Segmentation fault (core dumped)
```

**Comment by JohnDMcMaster** [comment]
A non thread safe log() can look like this:

```
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
```

**Comment by JohnDMcMaster** [comment]
```
PYUSCOPE_CHECK_THREADS=Y ./app/argus.py --microscope lip-a2
...
Traceback (most recent call last):
  File "/home/mcmaster/doc/ext/pyuscope-rhodium/uscope/gst_util.py", line 192, in render_cb
    self.user_cb(self.next_image_id)
  File "/home/mcmaster/doc/ext/pyuscope-rhodium/uscope/gui/imaging.py", line 1653, in emitSnapshotCaptured
    self.ac.log('Image captured: %s' % image_id)
  File "/home/mcmaster/doc/ext/pyuscope-rhodium/uscope/gui/common.py", line 373, in log
    log(s, newline=newline)
  File "/home/mcmaster/doc/ext/pyuscope-rhodium/uscope/gui/imaging.py", line 1880, in log
    self.ac.check_thread_safety()
  File "/home/mcmaster/doc/ext/pyuscope-rhodium/uscope/gui/common.py", line 344, in check_thread_safety
    assert self.main_thread == threading.get_ident(), (
AssertionError: ('GUI thread unsafe access detected', 139831542081344, 139830538626816)
```

**Comment by JohnDMcMaster** [comment]
Fixed above. These were several log messages that were issues in callbacks. One of them for example was in gstreamer thread context which is not necessarily the main thread

Other: we should consider just always emitting log signal instead of now splitting between microscope.log (emits event / thread safe) and ac.log (directly writes to widget). Among things Qt uses "auto connection" by default which will bypass IPC and do the call inline if it sees that you are trying to communicate with the GUI thread

**Comment by JohnDMcMaster** [comment]
The crash on exit appears to be triggered by sending data to the image processing process

**Comment by JohnDMcMaster** [comment]
Exit crash is being observed on xy3p, but not xy2p

**Comment by JohnDMcMaster** [comment]
```
The program 'python3' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 2448 error_code 9 request_code 130 minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by JohnDMcMaster** [comment]
Made shutdown more graceful: "shutdown: MainWindow shutdown instead of ArgusCommon shutdown, more orchestrated"

Haven't seen a shutdown crash since this tweak, but needs more testing

**Comment by JohnDMcMaster** [comment]
someone suggested: https://github.com/google/sanitizers/wiki/AddressSanitizer

**Comment by JohnDMcMaster** [comment]
Another bad log has been identified:

```
GstGUIImager.get(): self.ac.log(f"WARNING: failed to get image ({type(e)}: {e}). Sleeping then retrying")
```

This function is supposed to be thread safe and is called form misc contexts. If the camera disconnects / time outs the warning can corrupt the GUI

**Comment by JohnDMcMaster** [comment]
All outstanding issues have been fixed. Keep an eye on this and re-open if more are found (and/or new ticket)
